sudo: false

language:
  - cpp

addons:
  apt:
    packages:
      - libboost-all-dev
    sources:
      - ubuntu-toolchain-r-test

before_install:
  - pip install --user cpp-coveralls

script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .
  - ./bin/RunTests

notifications:
  email: false